name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cloudfoundry/capi:ruby-units
    steps:
    - uses: actions/checkout@master
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
