name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cloudfoundry/capi:ruby-units
    steps:
    - uses: actions/checkout@master
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
